project:
  type: website
  output-dir: docs

website:
  title: "Pedro Borges"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - blog.qmd
      - publicacoes.qmd
      - midia.qmd
    tools:
      - icon: github
        href: https://github.com/pabsantos/homepage
    background: "white"
    foreground: "black"
  page-footer:
    left:
      - Licenciado sob CC BY-NC 4.0, pabsantos (2024)
    right:
      - Desenvolvido com Quarto
  search: false


format:
  html:
    theme: [cosmo, styles.scss]
    toc: false
    # mainfont: monospace
    backgroundcolor: "white"
    fontcolor: "black"
    linkcolor: "black"
    lang: pt-BR



